name: Hello world workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash 
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash 
  dockerize:
    runs-on: ubuntu-latest
    steps:
      
      - name: docker images
        run: docker images
      - name: docker elasticsearch
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1
      - name: docker images part 2
        run: docker images
  displaycontent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: display content 
        run: ls
      
      - name: display just
        run: ls ./check
      - name: display content 2 
        run: ls
      - name: display just 2
        run: cat just.txt
      
    
